# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: University of Michigan Mars Rover Team
email: rover@umich.edu
description: > # this means to ignore newlines until "baseurl:"
    The Michigan Mars Rover Team (MRover) competes in the annual University Rover Challenge. 
    In 2018, we placed 9th in the world and 3rd in the US. 
    Our mission is to inspire students to pursue space exploration and engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrover.org" # the base hostname & protocol for your site
twitter_username: umrover
github_username: umrover
instagram_username: umroverteam

# Our sponsors
collections:
    sponsors:

# Build settings
markdown: kramdown

#Make Jekyll build site to the docs folder, not mrover/_site
destination: ../docs

#include the CNAME file in builds so that it ends up in docs (so that Github Pages can display our website at the address mrover.org)
include: ["CNAME"]